# How to interpolate horizontally using Providentia format

In [1]:
import nes

## 1. Read data to interpolate

In [2]:
# Original path: /esarchive/recon/ecmwf/cams61/cams61_chimere_ph2/eu/hourly/sconco3/sconco3_201804.nc
# Regular lat-lon grid from CAMS 
source_path = '/gpfs/projects/bsc32/models/NES_tutorial_data/exp_sconco3_201804.nc'

In [3]:
source_grid = nes.open_netcdf(path=source_path, info=True)
source_grid

In [4]:
source_grid.variables

{'sconco3': {'data': None,
  'dimensions': ('time', 'lat', 'lon'),
  'dtype': dtype('float32'),
  'coordinates': 'lat lon',
  'grid_mapping': 'crs',
  'units': 'ppb'}}

In [5]:
source_grid.lat

{'data': masked_array(data=[30. , 30.2, 30.4, 30.6, 30.8, 31. , 31.2, 31.4, 31.6,
                    31.8, 32. , 32.2, 32.4, 32.6, 32.8, 33. , 33.2, 33.4,
                    33.6, 33.8, 34. , 34.2, 34.4, 34.6, 34.8, 35. , 35.2,
                    35.4, 35.6, 35.8, 36. , 36.2, 36.4, 36.6, 36.8, 37. ,
                    37.2, 37.4, 37.6, 37.8, 38. , 38.2, 38.4, 38.6, 38.8,
                    39. , 39.2, 39.4, 39.6, 39.8, 40. , 40.2, 40.4, 40.6,
                    40.8, 41. , 41.2, 41.4, 41.6, 41.8, 42. , 42.2, 42.4,
                    42.6, 42.8, 43. , 43.2, 43.4, 43.6, 43.8, 44. , 44.2,
                    44.4, 44.6, 44.8, 45. , 45.2, 45.4, 45.6, 45.8, 46. ,
                    46.2, 46.4, 46.6, 46.8, 47. , 47.2, 47.4, 47.6, 47.8,
                    48. , 48.2, 48.4, 48.6, 48.8, 49. , 49.2, 49.4, 49.6,
                    49.8, 50. , 50.2, 50.4, 50.6, 50.8, 51. , 51.2, 51.4,
                    51.6, 51.8, 52. , 52.2, 52.4, 52.6, 52.8, 53. , 53.2,
                    53.4, 53.6, 53.8, 54. , 54.2, 54.4, 54.6, 54.8, 55. ,
                    55.2, 55.4, 55.6, 55.8, 56. , 56.2, 56.4, 56.6, 56.8,
                    57. , 57.2, 57.4, 57.6, 57.8, 58. , 58.2, 58.4, 58.6,
                    58.8, 59. , 59.2, 59.4, 59.6, 59.8, 60. , 60.2, 60.4,
                    60.6, 60.8, 61. , 61.2, 61.4, 61.6, 61.8, 62. , 62.2,
                    62.4, 62.6, 62.8, 63. , 63.2, 63.4, 63.6, 63.8, 64. ,
                    64.2, 64.4, 64.6, 64.8, 65. , 65.2, 65.4, 65.6, 65.8,
                    66. , 66.2, 66.4, 66.6, 66.8, 67. , 67.2, 67.4, 67.6,
                    67.8, 68. , 68.2, 68.4, 68.6, 68.8, 69. , 69.2, 69.4,
                    69.6, 69.8, 70. , 70.2, 70.4, 70.6, 70.8, 71. , 71.2,
                    71.4, 71.6, 71.8, 72. ],
              mask=False,
        fill_value=1e+20),
 'dimensions': ('lat',),
 'dtype': dtype('float64'),
 'standard_name': 'latitude',
 'long_name': 'Latitude',
 'units': 'degrees_north',
 'axis': 'Y'}

In [6]:
source_grid.lon

{'data': masked_array(data=[-25. , -24.8, -24.6, -24.4, -24.2, -24. , -23.8, -23.6,
                    -23.4, -23.2, -23. , -22.8, -22.6, -22.4, -22.2, -22. ,
                    -21.8, -21.6, -21.4, -21.2, -21. , -20.8, -20.6, -20.4,
                    -20.2, -20. , -19.8, -19.6, -19.4, -19.2, -19. , -18.8,
                    -18.6, -18.4, -18.2, -18. , -17.8, -17.6, -17.4, -17.2,
                    -17. , -16.8, -16.6, -16.4, -16.2, -16. , -15.8, -15.6,
                    -15.4, -15.2, -15. , -14.8, -14.6, -14.4, -14.2, -14. ,
                    -13.8, -13.6, -13.4, -13.2, -13. , -12.8, -12.6, -12.4,
                    -12.2, -12. , -11.8, -11.6, -11.4, -11.2, -11. , -10.8,
                    -10.6, -10.4, -10.2, -10. ,  -9.8,  -9.6,  -9.4,  -9.2,
                     -9. ,  -8.8,  -8.6,  -8.4,  -8.2,  -8. ,  -7.8,  -7.6,
                     -7.4,  -7.2,  -7. ,  -6.8,  -6.6,  -6.4,  -6.2,  -6. ,
                     -5.8,  -5.6,  -5.4,  -5.2,  -5. ,  -4.8,  -4.6,  -4.4,
                     -4.2,  -4. ,  -3.8,  -3.6,  -3.4,  -3.2,  -3. ,  -2.8,
                     -2.6,  -2.4,  -2.2,  -2. ,  -1.8,  -1.6,  -1.4,  -1.2,
                     -1. ,  -0.8,  -0.6,  -0.4,  -0.2,   0. ,   0.2,   0.4,
                      0.6,   0.8,   1. ,   1.2,   1.4,   1.6,   1.8,   2. ,
                      2.2,   2.4,   2.6,   2.8,   3. ,   3.2,   3.4,   3.6,
                      3.8,   4. ,   4.2,   4.4,   4.6,   4.8,   5. ,   5.2,
                      5.4,   5.6,   5.8,   6. ,   6.2,   6.4,   6.6,   6.8,
                      7. ,   7.2,   7.4,   7.6,   7.8,   8. ,   8.2,   8.4,
                      8.6,   8.8,   9. ,   9.2,   9.4,   9.6,   9.8,  10. ,
                     10.2,  10.4,  10.6,  10.8,  11. ,  11.2,  11.4,  11.6,
                     11.8,  12. ,  12.2,  12.4,  12.6,  12.8,  13. ,  13.2,
                     13.4,  13.6,  13.8,  14. ,  14.2,  14.4,  14.6,  14.8,
                     15. ,  15.2,  15.4,  15.6,  15.8,  16. ,  16.2,  16.4,
                     16.6,  16.8,  17. ,  17.2,  17.4,  17.6,  17.8,  18. ,
                     18.2,  18.4,  18.6,  18.8,  19. ,  19.2,  19.4,  19.6,
                     19.8,  20. ,  20.2,  20.4,  20.6,  20.8,  21. ,  21.2,
                     21.4,  21.6,  21.8,  22. ,  22.2,  22.4,  22.6,  22.8,
                     23. ,  23.2,  23.4,  23.6,  23.8,  24. ,  24.2,  24.4,
                     24.6,  24.8,  25. ,  25.2,  25.4,  25.6,  25.8,  26. ,
                     26.2,  26.4,  26.6,  26.8,  27. ,  27.2,  27.4,  27.6,
                     27.8,  28. ,  28.2,  28.4,  28.6,  28.8,  29. ,  29.2,
                     29.4,  29.6,  29.8,  30. ,  30.2,  30.4,  30.6,  30.8,
                     31. ,  31.2,  31.4,  31.6,  31.8,  32. ,  32.2,  32.4,
                     32.6,  32.8,  33. ,  33.2,  33.4,  33.6,  33.8,  34. ,
                     34.2,  34.4,  34.6,  34.8,  35. ,  35.2,  35.4,  35.6,
                     35.8,  36. ,  36.2,  36.4,  36.6,  36.8,  37. ,  37.2,
                     37.4,  37.6,  37.8,  38. ,  38.2,  38.4,  38.6,  38.8,
                     39. ,  39.2,  39.4,  39.6,  39.8,  40. ,  40.2,  40.4,
                     40.6,  40.8,  41. ,  41.2,  41.4,  41.6,  41.8,  42. ,
                     42.2,  42.4,  42.6,  42.8,  43. ,  43.2,  43.4,  43.6,
                     43.8,  44. ,  44.2,  44.4,  44.6,  44.8,  45. ],
              mask=False,
        fill_value=1e+20),
 'dimensions': ('lon',),
 'dtype': dtype('float64'),
 'standard_name': 'longitude',
 'long_name': 'Longitude',
 'units': 'degrees_east',
 'axis': 'X'}

In [7]:
source_grid.load()

Rank 000: Loading sconco3 var (1/1)
Rank 000: Loaded sconco3 var ((720, 1, 211, 351))

In [8]:
source_grid.to_shapefile(path='model_shp', var_list=['sconco3'])

/esarchive/scratch/avilanova/software/NES/nes/nc_projections/default_nes.py:3015: UserWarning: No vertical level has been specified. The first one will be selected.
  warnings.warn(msg)
/esarchive/scratch/avilanova/software/NES/nes/nc_projections/default_nes.py:3026: UserWarning: No time has been specified. The first one will be selected.
  warnings.warn(msg)

In [9]:
source_grid.shapefile

                                                geometry    sconco3
FID
0      POLYGON ((-25.10000 29.90000, -24.90000 29.900...  53.734375
1      POLYGON ((-24.90000 29.90000, -24.70000 29.900...  53.718746
2      POLYGON ((-24.70000 29.90000, -24.50000 29.900...  53.656250
3      POLYGON ((-24.50000 29.90000, -24.30000 29.900...  53.531246
4      POLYGON ((-24.30000 29.90000, -24.10000 29.900...  53.281250
...                                                  ...        ...
74056  POLYGON ((44.10000 71.90000, 44.30000 71.90000...  42.718750
74057  POLYGON ((44.30000 71.90000, 44.50000 71.90000...  42.499996
74058  POLYGON ((44.50000 71.90000, 44.70000 71.90000...  42.203125
74059  POLYGON ((44.70000 71.90000, 44.90000 71.90000...  41.843746
74060  POLYGON ((44.90000 71.90000, 45.10000 71.90000...  41.453125

[74061 rows x 2 columns]

In [10]:
# Original path: /gpfs/projects/bsc32/AC_cache/obs/ghost/EBAS/1.3.3/hourly/sconco3/sconco3_201804.nc
# Points grid from EBAS network
dst_grid_path = '/gpfs/projects/bsc32/models/NES_tutorial_data/obs_sconco3_201804.nc'
dst_grid = nes.open_netcdf(path=dst_grid_path, info=True)
dst_grid

/esarchive/scratch/avilanova/software/NES/nes/load_nes.py:73: UserWarning: Parallel method cannot be 'Y' to create points NES. Setting it to 'X'
  warnings.warn("Parallel method cannot be 'Y' to create points NES. Setting it to 'X'")

In [11]:
dst_grid.lat

{'data': masked_array(data=[-64.24006   , -54.84846497,  47.76666641,  46.677778  ,
                     48.721111  ,  47.529167  ,  47.05407   ,  47.348056  ,
                     47.973056  ,  48.878611  ,  48.106111  ,  48.371111  ,
                     48.334722  ,  48.050833  ,  47.838611  ,  47.040277  ,
                     47.06694444,  49.877778  ,  50.629421  ,  50.503333  ,
                     41.695833  ,  32.27000046,  80.05000305,  46.5475    ,
                     46.813056  ,  47.479722  ,  47.049722  ,  47.0675    ,
                     47.18961391, -30.17254   ,  16.86403   ,  35.0381    ,
                     49.73508444,  49.573394  ,  49.066667  ,  54.925556  ,
                     52.802222  ,  47.914722  ,  53.166667  ,  50.65      ,
                     54.4368    ,  47.80149841,  47.4165    , -70.666     ,
                     54.746495  ,  81.6       ,  55.693588  ,  72.58000183,
                     56.290424  ,  59.5       ,  58.383333  ,  39.54694   ,
                     42.72056   ,  39.87528   ,  37.23722   ,  43.43917   ,
                     41.27417   ,  42.31917   ,  38.47278   ,  39.08278   ,
                     41.23889   ,  41.39389   ,  42.63472   ,  37.05194   ,
                     28.309     ,  59.779167  ,  60.53002   ,  66.320278  ,
                     67.97333333,  48.5       ,  49.9       ,  47.266667  ,
                     43.616667  ,  47.3       ,  46.65      ,  45.        ,
                     45.8       ,  48.633333  ,  42.936667  ,  44.56944444,
                     46.81472778,  45.772223  ,  55.313056  ,  54.443056  ,
                     50.596389  ,  54.334444  ,  57.734444  ,  52.503889  ,
                     55.858611  ,  53.398889  ,  50.792778  ,  52.293889  ,
                     51.781784  ,  52.298333  ,  55.79216   ,  52.950556  ,
                     51.778056  ,  60.13922   ,  51.149617  ,  38.366667  ,
                     35.316667  ,  46.966667  ,  46.91      ,  -0.20194   ,
                     51.939722  ,  53.32583   ,  45.8       ,  44.183333  ,
                     37.571111  ,  42.805462  , -69.005     ,  39.0319    ,
                     24.2883    ,  24.466941  ,  36.53833389,  33.293917  ,
                     55.37611111,  56.161944  ,  57.135278  ,  36.0722    ,
                     52.083333  ,  53.333889  ,  51.541111  ,  52.3       ,
                     51.974444  ,  58.38853   ,  65.833333  ,  62.783333  ,
                     78.90715   ,  59.        ,  69.45      ,  59.2       ,
                     60.372386  , -72.0117    ,  59.2       , -41.40819168,
                    -77.83200073, -45.0379982 ,  51.814408  ,  50.736444  ,
                     54.753894  ,  54.15      ,  43.4       ,  71.58616638,
                     63.85      ,  67.883333  ,  57.394     ,  57.1645    ,
                     57.9525    ,  56.0429    ,  60.0858    ,  57.816667  ,
                     64.25      ,  59.728     ,  45.566667  ,  46.428611  ,
                     46.299444  ,  48.933333  ,  49.15      ,  49.05      ,
                     47.96      ,  71.32301331,  40.12498   ,  19.53623009,
                    -89.99694824,  41.05410004,  21.5731    , -34.35348   ],
              mask=False,
        fill_value=1e+20),
 'dimensions': ('station',),
 'dtype': dtype('float64'),
 'standard_name': 'latitude',
 'long_name': 'latitude',
 'units': 'decimal degrees North',
 'description': 'Geodetic latitude of measuring instrument, in decimal degrees North, following the stated horizontal datum.',
 'axis': 'Y'}

In [12]:
dst_grid.lon

{'data': masked_array(data=[-5.66247800e+01, -6.83106918e+01,  1.67666664e+01,
                     1.29722220e+01,  1.59422220e+01,  9.92666700e+00,
                     1.29579400e+01,  1.58822220e+01,  1.30161110e+01,
                     1.50466670e+01,  1.59194440e+01,  1.55466670e+01,
                     1.67305560e+01,  1.66766670e+01,  1.44413890e+01,
                     1.43300000e+01,  1.54936111e+01,  5.20361100e+00,
                     6.00101900e+00,  4.98944400e+00,  2.47386110e+01,
                    -6.48799973e+01, -8.64166565e+01,  7.98500000e+00,
                     6.94472200e+00,  8.90472200e+00,  6.97944400e+00,
                     8.46388900e+00,  8.17543368e+00, -7.07992300e+01,
                    -2.48675200e+01,  3.30578000e+01,  1.60341969e+01,
                     1.50802780e+01,  1.36000000e+01,  8.30972200e+00,
                     1.07594440e+01,  7.90861100e+00,  1.30333330e+01,
                     1.07666670e+01,  1.27249000e+01,  1.10096197e+01,
                     1.09796400e+01, -8.26600000e+00,  1.07361600e+01,
                    -1.66700000e+01,  1.20857970e+01, -3.84799995e+01,
                     8.42748600e+00,  2.59000000e+01,  2.18166670e+01,
                    -4.35056000e+00, -8.92361000e+00,  4.31639000e+00,
                    -3.53417000e+00, -4.85000000e+00, -3.14250000e+00,
                     3.31583000e+00, -6.92361000e+00, -1.10111000e+00,
                    -5.89750000e+00,  7.34720000e-01, -7.70472000e+00,
                    -6.55528000e+00, -1.64994000e+01,  2.13772220e+01,
                     2.76675400e+01,  2.94016670e+01,  2.41161111e+01,
                     7.13333300e+00,  4.63333300e+00,  4.08333300e+00,
                     1.83333000e-01,  6.83333300e+00, -7.50000000e-01,
                     6.46666700e+00,  2.06666700e+00, -4.50000000e-01,
                     1.41944000e-01,  5.27897222e+00,  2.61000833e+00,
                     2.96488600e+00, -3.20416700e+00, -7.87000000e+00,
                    -3.71305600e+00, -8.07500000e-01, -4.77444400e+00,
                    -3.03305600e+00, -3.20500000e+00, -1.75333300e+00,
                     1.79444000e-01,  1.46305600e+00, -4.69146200e+00,
                     2.92778000e-01, -3.24290000e+00,  1.12194400e+00,
                     1.08223000e+00, -1.18531900e+00, -1.43822800e+00,
                     2.30833330e+01,  2.56666670e+01,  1.95833330e+01,
                     1.63200000e+01,  1.00318100e+02, -1.02444440e+01,
                    -9.89944000e+00,  8.63333300e+00,  1.07000000e+01,
                     1.26597220e+01,  1.25656450e+01,  3.95905556e+01,
                     1.41822200e+02,  1.53983300e+02,  1.23010872e+02,
                     1.26330002e+02,  1.26163111e+02,  2.10305556e+01,
                     2.11730560e+01,  2.59055560e+01,  1.42184000e+01,
                     6.56666700e+00,  6.27722200e+00,  5.85361100e+00,
                     4.50000000e+00,  4.92361100e+00,  8.25200000e+00,
                     1.39166670e+01,  8.88333300e+00,  1.18866800e+01,
                     1.15333330e+01,  3.00333330e+01,  5.20000000e+00,
                     1.10781420e+01,  2.53510000e+00,  9.51666700e+00,
                     1.74870804e+02,  1.66660004e+02,  1.69684006e+02,
                     2.19724190e+01,  1.57395000e+01,  1.75342640e+01,
                     2.20666670e+01,  2.19500000e+01,  1.28918823e+02,
                     1.53333330e+01,  2.10666670e+01,  1.19140000e+01,
                     1.47825000e+01,  1.24030000e+01,  1.31480000e+01,
                     1.75052800e+01,  1.55666670e+01,  1.97666670e+01,
                     1.54720000e+01,  1.48666670e+01,  1.50033330e+01,
                     1.45386110e+01,  1.95833330e+01,  2.02833330e+01,
                     2.22666670e+01,  1.78605560e+01, -1.56611465e+02,
                    -1.05236800e+02, -1.55576157e+02, -2.47999992e+01,
                    -1.24151001e+02,  1.03515700e+02,  1.84896800e+01],
              mask=False,
        fill_value=1e+20),
 'dimensions': ('station',),
 'dtype': dtype('float64'),
 'standard_name': 'longitude',
 'long_name': 'longitude',
 'units': 'decimal degrees East',
 'description': 'Geodetic longitude of measuring instrument, in decimal degrees East, following the stated horizontal datum.',
 'axis': 'X'}

In [13]:
source_grid.variables

{'sconco3': {'data': array([[[[53.734375, 53.718746, 53.65625 , ..., 56.859375, 56.29687 ,
            55.890625],
           [53.79687 , 53.71875 , 53.64062 , ..., 56.281246, 55.65625 ,
            54.98437 ],
           [53.8125  , 53.79687 , 53.671875, ..., 54.75    , 54.718746,
            54.09375 ],
           ...,
           [49.125   , 49.843746, 50.640625, ..., 41.609375, 41.468746,
            41.3125  ],
           [48.57812 , 49.46875 , 51.01562 , ..., 41.687496, 41.484375,
            41.343746],
           [50.921875, 50.95312 , 50.8125  , ..., 42.203125, 41.843746,
            41.453125]]],


         [[[53.812496, 53.875   , 53.874996, ..., 56.187496, 55.421875,
            54.843746],
           [53.828125, 53.92187 , 53.875   , ..., 54.921875, 54.499996,
            53.765625],
           [53.843746, 53.90625 , 53.89062 , ..., 52.85937 , 53.34375 ,
            53.062496],
           ...,
           [49.26562 , 49.859375, 50.60937 , ..., 41.781246, 41.6875  ,
            41.656246],
           [48.765625, 49.60937 , 51.015625, ..., 42.03125 , 41.843746,
            41.671875],
           [50.95312 , 50.9375  , 50.79687 , ..., 42.562496, 42.140625,
            41.781246]]],


         [[[53.546875, 53.593746, 53.65625 , ..., 55.140625, 54.499996,
            53.96875 ],
           [53.562496, 53.625   , 53.76562 , ..., 53.156246, 52.9375  ,
            52.57812 ],
           [53.546875, 53.624996, 53.734375, ..., 50.96875 , 51.79687 ,
            51.828125],
           ...,
           [49.3125  , 49.843746, 50.46875 , ..., 42.25    , 42.14062 ,
            42.03125 ],
           [48.874996, 49.578125, 50.92187 , ..., 42.17187 , 42.0625  ,
            42.031246],
           [50.859375, 50.874996, 50.75    , ..., 42.84375 , 42.48437 ,
            42.125   ]]],


         ...,


         [[[53.374996, 53.5625  , 53.374996, ..., 54.67187 , 54.734375,
            54.687496],
           [53.28125 , 53.593746, 53.59375 , ..., 54.5625  , 54.749996,
            54.71875 ],
           [53.29687 , 53.625   , 53.687496, ..., 54.73437 , 55.140625,
            55.01562 ],
           ...,
           [51.35937 , 50.96875 , 50.76562 , ..., 40.781246, 40.671875,
            40.624996],
           [51.015625, 50.70312 , 50.625   , ..., 40.515625, 40.48437 ,
            40.40625 ],
           [50.20312 , 50.25    , 50.67187 , ..., 40.39062 , 40.34375 ,
            40.343746]]],


         [[[53.015625, 53.39062 , 53.421875, ..., 54.28125 , 54.374996,
            54.171875],
           [52.968746, 53.296875, 53.562496, ..., 54.17187 , 54.3125  ,
            54.218746],
           [52.921875, 53.29687 , 53.546875, ..., 54.703125, 54.812496,
            54.375   ],
           ...,
           [51.59375 , 51.29687 , 50.84375 , ..., 41.171875, 41.124996,
            41.109375],
           [51.14062 , 50.9375  , 50.749996, ..., 40.968746, 40.90625 ,
            40.906246],
           [50.390625, 50.406246, 50.703125, ..., 40.65625 , 40.624996,
            40.59375 ]]],


         [[[52.749996, 53.0625  , 53.374996, ..., 53.999996, 53.96875 ,
            53.781246],
           [52.6875  , 52.968746, 53.359375, ..., 53.703125, 53.76562 ,
            53.65625 ],
           [52.64062 , 52.890625, 53.312496, ..., 54.249996, 54.109375,
            53.54687 ],
           ...,
           [51.73437 , 51.59375 , 51.14062 , ..., 41.468746, 41.421875,
            41.42187 ],
           [51.09375 , 50.92187 , 50.796875, ..., 41.078125, 41.04687 ,
            41.015625],
           [50.374996, 50.359375, 50.60937 , ..., 40.76562 , 40.71875 ,
            40.718746]]]], dtype=float32),
  'dimensions': ('time', 'lat', 'lon'),
  'dtype': dtype('float32'),
  'coordinates': 'lat lon',
  'grid_mapping': 'crs',
  'units': 'ppb'}}

## 2. Horizontal interpolation

In [14]:
interpolated_source_grid = source_grid.interpolate_horizontal(dst_grid, weight_matrix_path=None, 
                                                              kind='NearestNeighbour', n_neighbours=4,
                                                              info=True, to_providentia=True)

Creating Weight Matrix
Weight Matrix done!
Applying weights
	sconco3 horizontal interpolation
Formatting

In [15]:
interpolated_source_grid.lat

{'data': masked_array(data=[-64.24006   , -54.84846497,  47.76666641,  46.677778  ,
                     48.721111  ,  47.529167  ,  47.05407   ,  47.348056  ,
                     47.973056  ,  48.878611  ,  48.106111  ,  48.371111  ,
                     48.334722  ,  48.050833  ,  47.838611  ,  47.040277  ,
                     47.06694444,  49.877778  ,  50.629421  ,  50.503333  ,
                     41.695833  ,  32.27000046,  80.05000305,  46.5475    ,
                     46.813056  ,  47.479722  ,  47.049722  ,  47.0675    ,
                     47.18961391, -30.17254   ,  16.86403   ,  35.0381    ,
                     49.73508444,  49.573394  ,  49.066667  ,  54.925556  ,
                     52.802222  ,  47.914722  ,  53.166667  ,  50.65      ,
                     54.4368    ,  47.80149841,  47.4165    , -70.666     ,
                     54.746495  ,  81.6       ,  55.693588  ,  72.58000183,
                     56.290424  ,  59.5       ,  58.383333  ,  39.54694   ,
                     42.72056   ,  39.87528   ,  37.23722   ,  43.43917   ,
                     41.27417   ,  42.31917   ,  38.47278   ,  39.08278   ,
                     41.23889   ,  41.39389   ,  42.63472   ,  37.05194   ,
                     28.309     ,  59.779167  ,  60.53002   ,  66.320278  ,
                     67.97333333,  48.5       ,  49.9       ,  47.266667  ,
                     43.616667  ,  47.3       ,  46.65      ,  45.        ,
                     45.8       ,  48.633333  ,  42.936667  ,  44.56944444,
                     46.81472778,  45.772223  ,  55.313056  ,  54.443056  ,
                     50.596389  ,  54.334444  ,  57.734444  ,  52.503889  ,
                     55.858611  ,  53.398889  ,  50.792778  ,  52.293889  ,
                     51.781784  ,  52.298333  ,  55.79216   ,  52.950556  ,
                     51.778056  ,  60.13922   ,  51.149617  ,  38.366667  ,
                     35.316667  ,  46.966667  ,  46.91      ,  -0.20194   ,
                     51.939722  ,  53.32583   ,  45.8       ,  44.183333  ,
                     37.571111  ,  42.805462  , -69.005     ,  39.0319    ,
                     24.2883    ,  24.466941  ,  36.53833389,  33.293917  ,
                     55.37611111,  56.161944  ,  57.135278  ,  36.0722    ,
                     52.083333  ,  53.333889  ,  51.541111  ,  52.3       ,
                     51.974444  ,  58.38853   ,  65.833333  ,  62.783333  ,
                     78.90715   ,  59.        ,  69.45      ,  59.2       ,
                     60.372386  , -72.0117    ,  59.2       , -41.40819168,
                    -77.83200073, -45.0379982 ,  51.814408  ,  50.736444  ,
                     54.753894  ,  54.15      ,  43.4       ,  71.58616638,
                     63.85      ,  67.883333  ,  57.394     ,  57.1645    ,
                     57.9525    ,  56.0429    ,  60.0858    ,  57.816667  ,
                     64.25      ,  59.728     ,  45.566667  ,  46.428611  ,
                     46.299444  ,  48.933333  ,  49.15      ,  49.05      ,
                     47.96      ,  71.32301331,  40.12498   ,  19.53623009,
                    -89.99694824,  41.05410004,  21.5731    , -34.35348   ],
              mask=False,
        fill_value=1e+20)}

In [16]:
interpolated_source_grid.lon

{'data': masked_array(data=[-5.66247800e+01, -6.83106918e+01,  1.67666664e+01,
                     1.29722220e+01,  1.59422220e+01,  9.92666700e+00,
                     1.29579400e+01,  1.58822220e+01,  1.30161110e+01,
                     1.50466670e+01,  1.59194440e+01,  1.55466670e+01,
                     1.67305560e+01,  1.66766670e+01,  1.44413890e+01,
                     1.43300000e+01,  1.54936111e+01,  5.20361100e+00,
                     6.00101900e+00,  4.98944400e+00,  2.47386110e+01,
                    -6.48799973e+01, -8.64166565e+01,  7.98500000e+00,
                     6.94472200e+00,  8.90472200e+00,  6.97944400e+00,
                     8.46388900e+00,  8.17543368e+00, -7.07992300e+01,
                    -2.48675200e+01,  3.30578000e+01,  1.60341969e+01,
                     1.50802780e+01,  1.36000000e+01,  8.30972200e+00,
                     1.07594440e+01,  7.90861100e+00,  1.30333330e+01,
                     1.07666670e+01,  1.27249000e+01,  1.10096197e+01,
                     1.09796400e+01, -8.26600000e+00,  1.07361600e+01,
                    -1.66700000e+01,  1.20857970e+01, -3.84799995e+01,
                     8.42748600e+00,  2.59000000e+01,  2.18166670e+01,
                    -4.35056000e+00, -8.92361000e+00,  4.31639000e+00,
                    -3.53417000e+00, -4.85000000e+00, -3.14250000e+00,
                     3.31583000e+00, -6.92361000e+00, -1.10111000e+00,
                    -5.89750000e+00,  7.34720000e-01, -7.70472000e+00,
                    -6.55528000e+00, -1.64994000e+01,  2.13772220e+01,
                     2.76675400e+01,  2.94016670e+01,  2.41161111e+01,
                     7.13333300e+00,  4.63333300e+00,  4.08333300e+00,
                     1.83333000e-01,  6.83333300e+00, -7.50000000e-01,
                     6.46666700e+00,  2.06666700e+00, -4.50000000e-01,
                     1.41944000e-01,  5.27897222e+00,  2.61000833e+00,
                     2.96488600e+00, -3.20416700e+00, -7.87000000e+00,
                    -3.71305600e+00, -8.07500000e-01, -4.77444400e+00,
                    -3.03305600e+00, -3.20500000e+00, -1.75333300e+00,
                     1.79444000e-01,  1.46305600e+00, -4.69146200e+00,
                     2.92778000e-01, -3.24290000e+00,  1.12194400e+00,
                     1.08223000e+00, -1.18531900e+00, -1.43822800e+00,
                     2.30833330e+01,  2.56666670e+01,  1.95833330e+01,
                     1.63200000e+01,  1.00318100e+02, -1.02444440e+01,
                    -9.89944000e+00,  8.63333300e+00,  1.07000000e+01,
                     1.26597220e+01,  1.25656450e+01,  3.95905556e+01,
                     1.41822200e+02,  1.53983300e+02,  1.23010872e+02,
                     1.26330002e+02,  1.26163111e+02,  2.10305556e+01,
                     2.11730560e+01,  2.59055560e+01,  1.42184000e+01,
                     6.56666700e+00,  6.27722200e+00,  5.85361100e+00,
                     4.50000000e+00,  4.92361100e+00,  8.25200000e+00,
                     1.39166670e+01,  8.88333300e+00,  1.18866800e+01,
                     1.15333330e+01,  3.00333330e+01,  5.20000000e+00,
                     1.10781420e+01,  2.53510000e+00,  9.51666700e+00,
                     1.74870804e+02,  1.66660004e+02,  1.69684006e+02,
                     2.19724190e+01,  1.57395000e+01,  1.75342640e+01,
                     2.20666670e+01,  2.19500000e+01,  1.28918823e+02,
                     1.53333330e+01,  2.10666670e+01,  1.19140000e+01,
                     1.47825000e+01,  1.24030000e+01,  1.31480000e+01,
                     1.75052800e+01,  1.55666670e+01,  1.97666670e+01,
                     1.54720000e+01,  1.48666670e+01,  1.50033330e+01,
                     1.45386110e+01,  1.95833330e+01,  2.02833330e+01,
                     2.22666670e+01,  1.78605560e+01, -1.56611465e+02,
                    -1.05236800e+02, -1.55576157e+02, -2.47999992e+01,
                    -1.24151001e+02,  1.03515700e+02,  1.84896800e+01],
              mask=False,
        fill_value=1e+20)}

In [17]:
interpolated_source_grid.to_shapefile(path='interpolated_points_shp', var_list=['sconco3'])

/esarchive/scratch/avilanova/software/NES/nes/nc_projections/default_nes.py:3015: UserWarning: No vertical level has been specified. The first one will be selected.
  warnings.warn(msg)
/esarchive/scratch/avilanova/software/NES/nes/nc_projections/default_nes.py:3026: UserWarning: No time has been specified. The first one will be selected.
  warnings.warn(msg)

In [18]:
interpolated_source_grid.shapefile

                        geometry    sconco3
FID
0    POINT (-56.62478 -64.24006)  53.660180
1    POINT (-68.31069 -54.84846)  53.726555
2      POINT (16.76667 47.76667)  39.719934
3      POINT (12.97222 46.67778)  33.805122
4      POINT (15.94222 48.72111)  35.401011
..                           ...        ...
163  POINT (-155.57616 19.53623)  50.547116
164  POINT (-24.80000 -89.99695)  53.660154
165  POINT (-124.15100 41.05410)  50.316594
166   POINT (103.51570 21.57310)  36.253923
167   POINT (18.48968 -34.35348)  44.863281

[168 rows x 2 columns]